### PR TITLE
DrawFormattedText's flipVertical now works with FTGL plugin

### LINKED ISSUE #349: flipVertical failing for DrawFormattedText
Hi Mario,

I just found that flipVertical is not working the way it should. It works if the text is vertically centered on the screen, but it soon leaves the screen if not. You can use the following code to see the problem.

```
clear all
try
    InitializeMatlabOpenGL;
    [wpnt,wrect] = PsychImaging('OpenWindow', 0,255);
    
    DrawFormattedText(wpnt,'ptest',900,400,0,'','','','',1);
    DrawFormattedText(wpnt,'ptest',1000,400,0,'',1,'','',1);
    DrawFormattedText(wpnt,'ptest',1100,400,0,'','',1,'',1);
    
    DrawFormattedText(wpnt,'ptest',900,'center',0,'','','','',1);
    DrawFormattedText(wpnt,'ptest',1000,'center',0,'',1,'','',1);
    DrawFormattedText(wpnt,'ptest',1100,'center',0,'','',1,'',1);
    
    Screen('Flip',wpnt);
    
    KbStrokeWait;
    sca
catch me
    sca
    rethrow(me)
end
```
Notice that the results from the third DrawFormattedText call are not on the screen, but from the 6th is fine.
I don't think this is something about the logic in DrawFormattedText, that is simple and seems right. Maybe something is up with the text drawer Screen('DrawText') or so, with this changed model matrix. 

All the best,
Dee
P.S. no idea why righttoleft is true in all my example calls, but the same issue happens if it is not.

### PR DESCRIPTION
**Pull request by dcnieho**
The FTGL plugin internally uses a coordinate system with origin at bottom-left instead of top-left. We thus have to remap the position we flip the text around.

Resolves #349 (but keep that open as there is a deeper issue that at some point should be addressed).

### CODE REVIEW

**Comment by dcnieho** [comment]
I have now fixed this in the plugin code instead. I am not sure what happened with the file that it looks as completely changed, my local git only shows a small patch.

**Comment by dcnieho** [comment]
ok, fixed it up, clean commits for you to apply now. not sure what caused it, but using vim instead of visual studio solved the trouble. Guess VS is changing my line endings

File: PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp [hunk 1]
```diff
@@ -450,11 +449,7 @@ void PsychSetTextBGColor(int context, double* color)
 // renderbackend needs a different geometric setup:
 void PsychSetTextViewPort(int context, double xs, double ys, double w, double h)
```
Comment (kleinerm) [inline PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp]: Is there a good technical reason why PsychSetTextViewPort gets turned into a no-op? Otherwise i'd like it to stay.

**Comment by kleinerm** [comment]
Looks good (apart from the SetViewPort thing), haven't tested it yet. However, a release is pending and i don't want go through a recompile of C-Code at this point anymore. So you could either only provide the hacked DrawFormattedText.m as a pull for this release - or i apply it manually. And then next release with the plugin? Or it all waits for the next release cycle?

File: PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp (hunk 1 above)
Comment (dcnieho) [inline PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp]: Well, the double _vxs, _vys, _vw, _vh variables are no longer used anywhere (the normal PTB projection matrix is fine, and no messing with vertical positions is needed anymore), so no need to keep them around. I considered removing the whole PsychSetTextViewPort call completely, but realized it is a useful interface to have for possible later plugins. So just keep it, but let it do nothing is what i thought.

**Comment by dcnieho** [comment]
It may be good to apply only 6a1a5c1 (is it quick for you? else i could make a separate pull request), so a fix is out there in the next cycle. We've got at least one person needing this. I should then rebase this branch on the new master?

**Comment by kleinerm** [comment]
Separate pull request is nice, but i can also just manually copy and paste the change into the m-file.
Wrt. SetViewport, please leave it in, the interface might be useful at some point, so if it doesn't hurt the new flipVertical flag, no reason to remove it.

**Comment by dcnieho** [comment]
You've got a separate pull request now. Not that i am not removing the SetViewport call, just making it do nothing *for the FTGL plugin*, as the values provided are no longer needed. Is that ok for you?

**Comment by kleinerm** [comment]
No wrt. SetViewport. Doing nothing is not much better than removing it. You can't use it if you find a reason to use it.

**Comment by dcnieho** [comment]
Understood. Will revert those changes.

File: PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp (hunk 1 above)
Comment (kleinerm) [inline PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp]: That revert is incomplete. You don't set the projection matrix based on _vxs et al.

Comment (dcnieho) [inline PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp]: There is no need to set the projection matrix anymore, my changes make rendering work with the default top-left PTB projection matrix.

Comment (kleinerm) [inline PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp]: I understand that, but without setting it, you just created another version of a SetviewPort that does nothing if one wants to actually use it, so it would be pointless.

Comment (dcnieho) [inline PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp]: Ok, I see. It is dangerous (and annoying) to have something from which you expect a certain effect, only to find out later it doesn't do what it advertises. We don't know how this might be used later.

In that case, my projection matrix would be:
`gluOrtho2D(_vxs, _vxs + _vw, _vys + _vh, _vys);`
i.e., reversing the third and fourth argument so that it has an origin in top-left, consistent with the rest of PTB. Ok?

Comment (kleinerm) [inline PsychSourceGL/Cohorts/FTGLTextRenderer/libptbdrawtext_ftgl.cpp]: If it works, yes. We just have to be consistent across all potential future plugins, and so far the ViewPort setting wasn't doing anything spectacular, so should be fine. I'll only test this pull sometime later in the next release cycle.

Btw. i think some of the improvements you made wrt. building the plugin on Windows don't actually work with my msvc 2010 build environment. Unfortunately i can't remember what the problem was, it was already a couple of months ago, but i'll probably have to revert that commit until we upgrade to a more modern msvc version - and the resulting change in msvc runtime library versions etc.

**Comment by dcnieho** [comment]
Ok, now it should be ready, projection matrix is set based on provided viewport.

**Comment by dcnieho** [comment]
Not sure if bothering you too early after beta release, but how does the current state of this pull request look to you?
